### ISSUE TITLE
Show number of unique users per API

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#1003]
Show the the number of unique users

- Unique users per API visible in analytics dashboard
  - Unique users per all APIs owned
  - Unique user per a selected API (related to #999)

E.g. the 'unique users count' should update whenever the dashboard is filtered.

# User story
> As an API owner
I want to see the number of unique users for my API(s) 
so that I can use that figure to determine how popular my API(s) is/are and see any changes in popularity

# Design

![apinf analytics charts2](https://cloud.githubusercontent.com/assets/17976243/16450053/90ef7c8e-3e03-11e6-80a1-15f1ccf4b2a1.png)

# Definition of done
* [ ] When viewing statistics for all APIs (owned by the user), user can see the number of unique users for all those APIs
* [ ] When viewing a single API (owned by the user), user can see the number of unique users for that particular API

**Comment by Nazarah** [comment]
Do you need this information in details in the Dashboard menu itself?
Becasue currently APINF has a User side menu and we can always incorporate this in that place.
Other wise, we may need to have different page link from dashboard because too much information would clutter the view.
I suggest for showing an overview of unique users with a link to see the details.
Or this can be shown in a separate diqalogue as well.

**Comment by bajiat** [comment]
Users menu in Apinf is for Apinf administrators, not for API owners. 

The idea of unique users was just to show a number, nothing more, in dashboard. If possible, that number would change if user interacts with dashboard (e.g. selects a timeframe, changes the timeframe)

**Comment by brylie** [comment]
For this type of query, we probably need to store the analytics in a local collection. @frenchbread is currently working on storing the Elastic analytics in an local collection.
