### ISSUE TITLE
Setting for API visibility

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#1020]
Add a setting / option for API owner so that they can hide their API backend from catalog. This is one of the first steps from supporting not only open APIs but also closed APIs.

_Open issue: Should this setting be available in API profile view or in Edit API settings view?_

Related issue: #1207

# User story
> As an API owner 
I want to be able to select whether my API is publicly visible in the catalog or not

# Definition of done
* [ ] API owner has an option to select API visibility in catalog: visible or hidden (UI widget)
* [x] The API owner and Apinf administator(s) can easily see what is the current/selected visibility setting of API 
* [x] If API is hidden by owner, only administrators and the particular owner can see it in the catalog. It is hidden for all other users.
* [x] Not authorized users cannot view  the data: they will get a not authorized message

# Wireframe

![apivisibilityvisible](https://cloud.githubusercontent.com/assets/17976243/17473409/0b728766-5d59-11e6-9aeb-95c121cc075a.png)

![apivisibilityhidden](https://cloud.githubusercontent.com/assets/17976243/17473416/13c2be54-5d59-11e6-82f7-59de1d684fe6.png)

**Comment by nnn** [comment]
Interested in this task.

**Comment by nnn** [comment]
@jykae, can you take this task?

**Comment by jykae** [comment]
@nnn yes, I assign myself.

**Comment by jykae** [comment]
Going to use Bootstrap Switch http://www.bootstrap-switch.org/

**Comment by nnn** [comment]
@jykae, sounds good!

**Comment by Nazarah** [comment]
@bajiat When Administrator/API owner see the hidden API in catalog, should there be any specific icon/symbol indicating that the API is hidden from public view? This helps them to remind that which API is visible to public users and which is not. Specially useful for Admins since they might need to monitor 100s of APIs.

**Comment by nnn** [comment]
@Nazarah, not only an icon, color also can be a good indicator. Even better, an icon and color together.

**Comment by Nazarah** [comment]
Since the hidden APIs will only appear in Admin and API owner's catalog view, we can markdown only those specific APIs with a particular icon.
This way there is no need to provide icons/colors to public APIs in the grid and table view.
Suggestions are welcomed. :)

![apicardhidden](https://cloud.githubusercontent.com/assets/17976243/17475461/c51b1a3e-5d63-11e6-99f5-0e0f87698512.png)

![apiuptimetableyellow](https://cloud.githubusercontent.com/assets/17976243/17475472/d0485958-5d63-11e6-9f01-6fb961ede013.png)

**Comment by brylie** [comment]
I'm having trouble checking the user permission from within the `Router.onBeforeAction`. Basically, the API Backend object is not available before the template renders, so we cannot simply call `apiBackend.currentUserCanView()`. When trying to call a server method from within the onBeforeAction, I am getting errors, basically since the method is async. 

We may need to wait on the migration to FlowRouter before taking the current approach.
https://forums.meteor.com/t/how-to-wait-on-for-calling-meteor-methods/6871/6
