### ISSUE TITLE
Documentation link on API Backend documentation tab not working

### ISSUE THREAD

**Issue by Nazarah** [apinf/api-umbrella-dashboard#1133]
Windows 8, Chrome (latest)

Reproduction Steps:

1. Go to a API page and go to the documentation tab.
2. Click Manage.
3. Add link to a JSON file (http://petstore.swagger.io/v2/swagger.json) and save.
4. on Documentation Tab, click on the appeared URL.

Result: clicking doesn't redirect to the JSON file.
Expected: The link should function as normal clickable link and should direct the user to the documentation page on a new tab in the browser

**Comment by brylie** [comment]
On the API Backend Documentation tab, the 'Documentation Link' does not work as expected. 

# Observed behavior
When clicking the link, nothing happens. 

# Expected behavior
When clicking the link, the browser would navigate to the remote resource.

# Possible cause
The template file contains an anchor tag where the href value is #. The href value should be the url of the Documentation Link.
