### ISSUE TITLE
Add basic chart widget to API user dashboard

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#120]
Using chart widget from task #78, add placeholder chart to API user dashboard.

Definition of done
---
* [x] Insert chart template into API user dashboard template.
* [ ] Add any additional markup necessary.

**Comment by frenchbread** [comment]
Currently waiting for @elnzv to implement a sidebar for API user dashboard. So far I moved chart template to dashboard and removed routes and templates for posts. Here is the [branch](https://github.com/apinf/api-umbrella-dashboard/tree/feature/adding-chart-widget-to-dashboard).

**Comment by frenchbread** [comment]
Since the data from elastic search is accessible, I am now trying to pass the data from the server-side (`elasticSearch.js` file) to template on client-side through the [router](https://github.com/apinf/api-umbrella-dashboard/blob/64c329243c7c43a2b11f28d6752296a68bbe5b99/lib/router/main.js#L15) (`main.js`). For that approach, @elnzv suggested to use [reacrive-var](https://atmospherejs.com/meteor/reactive-var) package. Its functionality is very similar to Session. But the problem is that when I am [assigning](https://github.com/apinf/api-umbrella-dashboard/blob/64c329243c7c43a2b11f28d6752296a68bbe5b99/server/elasticSearch.js#L39) a variable inside `ES.search` method, it is not possible to read it [outside](https://github.com/apinf/api-umbrella-dashboard/blob/64c329243c7c43a2b11f28d6752296a68bbe5b99/server/elasticSearch.js#L48) the function, meaning that it comes as undefined. [ElasticSearch](https://atmospherejs.com/brishin/meteor-elasticsearch) package's documentation does not provide any additional info at this point. 

@brylie, Any suggestions or possible solutions? This is actually javascript issue, nothing to do with meteor here. Global variables did not work as well as Sessions.
Here is working [branch](https://github.com/apinf/api-umbrella-dashboard/tree/feature/adding-chart-widget-to-dashboard) and last [commit](https://github.com/apinf/api-umbrella-dashboard/commit/64c329243c7c43a2b11f28d6752296a68bbe5b99).
