### ISSUE TITLE
Nightly2: Documentation viewer showing link to Petstore Swagger instead of proper Swagger file

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#1409]
Steps to reproduce:
1. Log in to nightly2
2. Go to Catalog and select e.g. PTV Open Api  (or any API for which a Swagger file has been added prior to the newest deployment)
3. Open Documentation tab

Expected result:
The previously uploaded Swagger file is displayed in Swagger UI

Actual outcome:
Empty Swagger UI with link to Petstore is displayed

![swagger ui bug](https://cloud.githubusercontent.com/assets/11626388/17802639/130ba77e-65fa-11e6-9c89-a3d6a9cd2341.png)

**Comment by bajiat** [comment]
@brylie Can you provide further information about what you found out concerning the DocumentationID?

**Comment by brylie** [comment]
The API Backend document contains a `documentationFileId` field, with a valid value:

![screenshot from 2016-08-19 10-49-09](https://cloud.githubusercontent.com/assets/17307/17802782/edb678a4-65fa-11e6-9a29-63e0d1a13838.png)

However, the DocumentationFile does not appear in the client-side collection. This could be due to reasons such as:

- an error in the DocumentationFile publication/subscription
- the documentation file having been deleted from the server

**Comment by brylie** [comment]
One thing that may be related is that we switched how we handle file IDs recently. I do not remember the exact details, but it involved using the file MD5 in the route/ID. @nnn can you verify what changed with the DocumentationFiles IDs?

**Comment by bajiat** [comment]
@brylie Would that mean that the only way to fix this in nightly is to upload each of the Swagger files again in nightly2 (and also in nightly)?

**Comment by brylie** [comment]
@bajiat re-uploading the files would be a simple solution. I am not sure how we would otherwise fix the ID documentationFileId field mismatch.
