### ISSUE TITLE
Determine build schedule

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#173]
Users (including colleagues) may want to access release versions of our project. Create one or more pre-releases, as well as a schedule for pre-releases.

Definition of done
---
* [ ] Decide how often to issue pre-releases.
* [ ] Determine build schedule.
* [ ] Determine on what to achieve on scheduled builds (e.g. automated testing).
* [ ] Create build script based on determined build steps.
* [ ] Select build automation platform.
* [ ] Schedule build script on the selected automated platform.

**Comment by bajiat** [comment]
Aseem.

**Comment by ashakunt** [comment]
So, we had been discussing a couple of items during Monday with Jusso. And the conclusion was the following: 

Pre Requisite: Get Jenkins server up and running  with two major build streams. (1)  develop  or master branch. (2) feature branch

Build schedule:
* Every developer should be able to run the tests on the feature branch as and when needed.
* The develop / master branch tests are run nightly + on every SCM changes .
* It should also be possible for any developer to create their own testing job (but this should be temp) which runs on SCM changes.

In this way, we keep testing whenever there are changes and when there is need.

What is achieved in scheduled builds: 
* Automated testing is done on all SCM changes [what to test should be defined in a separate ticket, either as a sub task or otherwise]

Schedule of pre-release:
* All nightly builds, after success will be deployed to: nigthly.apinf.com
* All sprint deliveries will be deployed to: alpha.apinf.com (or some other name)

Build automation platform: 
* All the builds will happen on Ubuntu / Debian server 

Build scripts
* This should be taken as a sub task of this task with items like: 
* [] How are the tests run now?
* [] All the tests should run through one single wrapper

**Comment by brylie** [comment]
Great work! This is exciting :-)

**Comment by JuusoV** [comment]
Good stuff @ashakunt. I'm still waiting for @ccsr to delpoy the servers for me to configure for our use. 
Right now I am researching how can we deploy two meteor applications side by side on the server.
I will let you know as soon as I get the servers running so we can get more in depth with the deployment.

**Comment by JuusoV** [comment]
btw @ashakunt our chat server is down right now so we will have to figure out a way to communicate easily.

**Comment by ashakunt** [comment]
@JuusoV thanks for the update. Looks like the universe is conspiring us to use an IRC channel.

**Comment by JuusoV** [comment]
@ashakunt @brylie #Apinf @FreeNode

**Comment by ashakunt** [comment]
\o/

**Comment by brylie** [comment]
A [Jenkins deployment script example](https://forums.meteor.com/t/jenkins-shell-script-for-anyone-interested/6364) was just posted to the Meteor forums.

**Comment by ashakunt** [comment]
Hi, 

Based on all the discussions done above, the major part of this task has already been agreed. There are some smaller items which should now be implemented but IMHO, they should be treated as separate tasks. 

If everyone agrees, then I am going to create another tasks for the following items: 

* Writing of Unit (and/or) Functional tests in preferred framework
* Determine build steps for compilation (or setting up) of dashboard
* Wrapper script for running all the tests (python / shell / ruby)

**Comment by brylie** [comment]
Sounds good. 

We may need to consider how to run tests in Meteor, using the Velocity framework with Jasmine. We can discuss the details in the issue you create.

**Comment by ashakunt** [comment]
Created two stories, #200 and #201 for this purpose. Some parts of discussion are also going on in #174 . Closing this issue as the fine-grained discussions now move to their own stories.
