### ISSUE TITLE
Choose and implement map library

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#213]
Select an open source map library that could be utilized for example to visualize locations from which an API endpoint is used.

Definition of done
---
* [x] Compare at least two high-profile open source map libraries.
* [x] Choose one and document the reason for choosing the library.
* [x] Create template to use the map framework in our project.
* [x] Display location data in the map from our analytics.
  * [ ] Choropleth
  * [x] Heatmap

**Comment by JuusoV** [comment]
Interested.

**Comment by JuusoV** [comment]
[Huge discussion about the map libraries] (http://gis.stackexchange.com/questions/8032/how-do-various-javascript-mapping-libraries-compare) suggests that either go with Leaflet or Openlayers 3. Both being open source - of course.

*Leaflet is said to be easier to deploy and configure for simple usage.  Being said that  Leaflet is not that feature rich.

* OpenLayers 3 being very rich in features but the deployment is said to be more challenging. 

* Both of the projects have great documentation.

Now the question remains. How feature rich mapping do we need?

**Comment by JuusoV** [comment]
[Leaflet Chropleth example] (http://leafletjs.com/examples/choropleth.html)

**Comment by JuusoV** [comment]
I decided to run with Leaflet since its very light, simple and should be fairly easy to deploy. There is a nice heatmap available for Leaflet too. We really dont need all the available features of Openlayers.

**Comment by brylie** [comment]
So that you can move on past the base layer struggle, use a world borders file (in TopoJSON format). Here are a couple of resources describing how this works:

* [Loading and parsing TopoJSON data with Leaflet-Omnivore](https://www.mapbox.com/mapbox.js/example/v1.0.0/omnivore-topojson/)
* [leaflet-omnivore](https://github.com/mapbox/leaflet-omnivore)
* [Natural Earth World Atlas](https://github.com/mbostock/world-atlas)
