### ISSUE TITLE
Refresh heatmap when data is returned from ElasticSearch

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#322]
Currently the heatmap is only updated when the user interacts with the data, but it should be automatically updated when the data is returned from the query. 

Definition of done
---
* [ ] Determine the point when the map can be refreshed.
* [ ] Implement a hook to refresh the map when the data is available.
* [ ] Ensure that the map is refreshed every time data is filtered is interacting with charts.

**Comment by frenchbread** [comment]
"Refresh" function can be actually placed in filter.js file but the problem is that once leaflet map has been initialized it is not possible to reinitialize one. There is built in "update" function (within leaflet) but even if calling it, data/heat won't update. The solution I came up with that seemed to work is onFiler event, removing DOM element from the page and reinitialize leaflet map with fresh data. Not the best approach but at least this could work
