### ISSUE TITLE
Add route permission for editing api backend

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#369]
Before displaying API edit view, check if the user has permission to edit the API. If user does not have permission, show an error message.

Definition of done
---
* [x] Add router action to check that a user id is in the API managers list.
  * [x] Display an error message if the user is not allowed to edit the API.
  * [x] Render the form, if user is authorized to edit the API configurations.
* [x] Create route onBeforeAction using previously defined action.

**Comment by brylie** [comment]
@frenchbread, please provide us with a status update.

**Comment by frenchbread** [comment]
@brylie I'm having some difficulties here. I wrote the logic and it seems to be fine but it does not work as expected. I've created a PR #392 and labeled it as `WIP` so @apinf/developers could easily refer to it.
I have been troubleshooting it for a long time but nothing and need some help with this issue.

**Comment by brylie** [comment]
@frenchbread break the final step into parts.

1. Define a function in lib/_config/router.js such as the, based on [redirectToSignIn](https://github.com/apinf/api-umbrella-dashboard/blob/develop/lib/_config/router.js#L3).
1. Inside your method, [call to Meteor.error](https://github.com/brylie/meteor-accounts-admin-ui-bootstrap-3/blob/master/server/methods.js#L17) with an appropriate error number and descriptive text
1. Create a template to display an error to the user
1. Add your function to the [route onBeforeAction](https://github.com/apinf/api-umbrella-dashboard/blob/develop/lib/_config/router.js#L42), so the user is authorized before the route renders

If the user is authorized, the route `this.next()` should be called, so that the route works as expected for an authorized user.

**Comment by brylie** [comment]
Opened pull request #452
