### ISSUE TITLE
Allow yml and txt in API configuration import

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#415]
Currently, API configuration file upload only accepts yaml and json file extensions. Add yml and txt to allow these file stypes. Check also if there is a MIME type filter that would be simpler to adopt.

Definition of done
--
* [x] Check the current upload code.
* [x] Check for MIME type filter, e.g. text/plain.
* [x] Make required changes to allow relevant formats.

**Comment by elnzv** [comment]
Yml check is already in place.

**Comment by elnzv** [comment]
@frenchbread is it possible to add a txt files check? Does it make sense? Will it work with ace editor parsing?

**Comment by frenchbread** [comment]
@elnzv Yes, it is possible. I don't think that is will make any sense because import file must contain yaml or json object with correct syntax. But initial task was to allow importing `txt` file, so I will add this functionality.

> Will it work with ace editor parsing?

Yes. It will just require to modify code a little.

You can assign this issue to me since I am more familiar with it.

**Comment by bajiat** [comment]
@frenchbread @elnzv We created a new task for txt parsing. See #467. Let's focus on that later. When everything else is completed and the PR is merged, go ahead and close the task.
