### ISSUE TITLE
backends shown as offline

### ISSUE THREAD

**Issue by ccsr** [apinf/api-umbrella-dashboard#525]
All the backends are shows as offline. This is what is shown in KoodiViikko in Mikkeli. Attaching the screenshot 

![12119716_472210216294581_1615479348_o](https://cloud.githubusercontent.com/assets/10469538/10411596/a2d13aaa-6f73-11e5-84be-843cd4fcc0c3.jpg)

**Comment by ccsr** [comment]
Adding @kyyberi

**Comment by elnzv** [comment]
It is shown as down only on a first load.
If you reload the page it shows status correctly. 
@apinf/developers who was implementing this feature? What can cause this problem?

**Comment by frenchbread** [comment]
I've been implementing it. I think problem is caused by meteor. When the apiBackend page loads first time it request for status of specific api backend. But if navigating to another apiBackend page, api status will remain the same (for apiBackend that loaded first). Reloading the page can resolve this problem as @elnzv mentioned.

I will look into this issue.

**Comment by frenchbread** [comment]
@apinf/developers PR #526 created. Please review.
