### ISSUE TITLE
Implement downloadable log of API usage statistics in text format

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#536]
Create an export button to download Dashboard data. The downloaded data should only be reflecting the current status of the dashboard. For instance, if user has filtered the dashboard data by time etc., the download will only contain the filtered data.

Definition of done
------
* [x] Add button to dashboard layout.
  * [x] Start by creating a wireframe in our documentation repository (do not skip this step).
* [x] Add CSV library to project (see Papa Parse).
* [x] Create event to parse dashboard data to CSV.
  * [x] Ensure only filtered dashboard data is exported.

**Comment by kyyberi** [comment]
CSV format as an option would be nice. That enables import it to statistical analysis software. Also consider providing API access to Logs.

**Comment by frenchbread** [comment]
I am interested in this task.

**Comment by frenchbread** [comment]
This issue actually depends on others it term of that currently we do not have any Api Backend usage logs for being able to test sample queries.

The current field stack returned from elastic search looks like this:

```javascript
{ _index: '**index**',
    _type: '**type**',
    _id: '**_id**',
    _score: 1,
    _source: 
     { api_key: '**apiKey_id**',
       internal_gatekeeper_time: 17.1,
       internal_response_time: 39.7,
       user_email: '**user_email**',
       user_id: '**user_id**',
       user_registration_source: 'web',
       backend_response_time: 30,
       request_accept: 'application/json',
       request_at: '2015-10-01T01:16:24.758Z',
       request_connection: 'keep-alive',
       request_content_type: 'application/json',
       request_host: '**host**',
       request_ip: '**request_ip**',
       request_method: 'GET',
       request_scheme: 'https',
       request_size: 261,
       request_url: '**request_url**',
       response_age: 0,
       response_content_length: 9153,
       response_content_type: 'application/json; charset=utf-8',
       response_server: 'nginx',
       response_size: 9695,
       response_status: 200,
       response_time: 58,
       proxy_overhead: 28,
       request_ip_country: 'FI',
       request_ip_location: [Object],
       request_path: '**path**',
       request_query: {},
       request_hierarchy: [Object] 
     }
} 
```

And for now I am not sure, in case of apiBackend usage, will the apiBackend _id be populated in addition to those fields above. (Because as far as I understand we need to filter elastic search data by apiBackend ID).

PS. I changed the actual values in this object to `**field_name**`.

@apinf/developers Any ideas?

**Comment by frenchbread** [comment]
Implemented core functionality for logs export in csv format. I am going to and inline comments and publish PR later today.

Current branch: [`536-download-api-usage`](https://github.com/apinf/api-umbrella-dashboard/tree/feature/536-download-api-usage)

One addition that I think will be good to implement is a loading state for a button:
 * Since the conversion and data fetching takes some time, we need to notify user about the its status.

**Comment by brylie** [comment]
@frenchbread, you can ultimately decide how to implement this feature, e.g. using a new Elastic query if needed. Just keep in mind our ideas about filtering the data, and see if you can take that route. Thanks for taking this task!

**Comment by frenchbread** [comment]
Created the wire-frame and added it to [docs repo](https://github.com/apinf/docs/blob/master/docs/design/%23536_logs_export.png).

Here is the look:

![logs_export_btn_wireframe](https://cloud.githubusercontent.com/assets/2122679/10875680/ae4dc18e-8178-11e5-9326-d28eb5b9aa42.png)

I also updated the branch with improved functionality. Now user can export only filtered data with 5 fields provided, those field that are listed in the data table.

**Comment by frenchbread** [comment]
PR - #571
