### ISSUE TITLE
Brainstorm session about personas

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#6]

**Comment by brylie** [comment]
Related to #4

**Comment by bajiat** [comment]
I changed the time allocation for the task, because I need to reserve some time for preparing for the persona workshop. Since we don't have any user research material available, I'll try to gather some information about API users and owners, hoping that we would be able to utilise that in the workshop.

**Comment by brylie** [comment]
Here are a couple of quick links that might be useful to get a general sense of roles and needs:
* [API Management Personas](https://developer.ibm.com/apimanagement/docs/api-101/api-management-personas/)
* [User personas for HTTP APIs](https://www.mnot.net/blog/2012/04/14/user_personas_for_http_apis)
