### ISSUE TITLE
Get profile name when authenticating users via Github

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#64]
When authenticating users via Github, an object is returned with basic user details (email, etc). Get the user name (real name or otherwise) from the authentication object, and store it in our user profile. 

There is a [support request](https://github.com/Jabbslad/accounts-github/issues/5) with the upstream package relevant to this feature.

**Comment by frenchbread** [comment]
Username fetching is done, so after user is authenticated with github, username is stored in db.

The issue with "login error" with email is kind of solved in a way that for successful authentication user has to have public status assigned to his primary email address in GitHub profile settings. If it is not (if user does not want to share email address) an error saying "Please make you email address public in github settings" can be rised because otherwise nothing happends - no error, no authentication.

At the same time even the exception for using username instead of email address does not help. I think this is happening because accounts-github package uses email address as the only option for authenticating a user.

**Comment by brylie** [comment]
Excellent. Is there an issue we can open on the Meteor Boilerplate, so that yogiben is aware of this difficulty?

**Comment by nizyev** [comment]
Here is an example of Facebook permission request:

```
Meteor.loginWithFacebook({
    requestPermissions: ['email', 'user_birthday', 'user_location']
}, function(error){loginCallBack(error);});

```

**Comment by nizyev** [comment]
With Github (not sure will it work)
```
Meteor.loginWithGithub
  requestPermissions: ['email']
     (error) ->
       if error
         console.log("Login Error", error)
```

**Comment by brylie** [comment]
Meteor [accounts-github](https://github.com/meteor/meteor/blob/devel/packages/accounts-github) extends the [accounts-oauth](https://github.com/meteor/meteor/tree/devel/packages/accounts-oauth) package. 

The *accounts-oauth* `loginWithExternalService` method takes an `options` object as the first paramater, which may contain a [request permissions array](https://github.com/meteor/meteor/blob/devel/packages/accounts-oauth/oauth_client.js#L10). 

As @nizyev demonstrated above, it may be possible to get access to a Github user's private email by requesting the **email** permission during login.

**Comment by nizyev** [comment]
Also take a look in [Meteor Cheatsheet] (https://gist.github.com/LeCoupa/9955478#file-meteor-cheatsheet-coffee-L88)

**Comment by nizyev** [comment]
[Here](http://stackoverflow.com/a/24692465) is the same issue with solution.

**Comment by jykae** [comment]
Where is PR & solution for this? I have to re-open this.

**Comment by brylie** [comment]
@frenchbread or @elnzv can you recall why this issue was closed? We still want to fetch user information from Github, when available.

**Comment by frenchbread** [comment]
I think it was just misunderstanding in terms of `username` and `user name`..

**Comment by frenchbread** [comment]
If @jykae will remain taking this issue here is a useful reference for [GitHub docs - Users](https://developer.github.com/v3/users/). So fetching user's Name and writing it into a collection should not be a big deal. 

Also, all the changes that are required for this to work are at [`/server/accounts.js`](https://github.com/apinf/api-umbrella-dashboard/blob/develop/server/accounts.js) file.
