### ISSUE TITLE
Implement database query and view for showing latest API backends

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#687]
As a part of the front-page re-design we need a view of the newest additions to API catalog. This requires both a query (publication and subscription) and a view.

* [x] Create publication
* [x] Create subscription 
* [x] Create temporary route (For testing purposes, until home page is redesigned) 
* [x] Create template
* [x] Use specific query that contains sorting by `created_at` field & limit amount of returned documents, for example to 6.
* [ ] Integrate `latestApiBackends` template to a redesigned home page.

**Comment by frenchbread** [comment]
Interested in this one.

**Comment by bajiat** [comment]
@frenchbread Are you still interested? Might require a schema update so that we have a creation date for API backends.

**Comment by frenchbread** [comment]
Self-assigned.

Creation timestamp field for API backends should be already present in a schema.

**Comment by frenchbread** [comment]
Created a PR #727 with `WIP` label.

The reason for `WIP` label is that since we do not have a redesigned version of a home page yet, there is no actual place where to put `latestApiBackends` template. For that reason I've added a temporary route `/latest` for testing.

Does it make sense to keep the PR in `WIP` until the new design is submitted? Or we can merge it now and do related integrations later?
