### ISSUE TITLE
Elasticsearch is trying to access loggedin user's "profile" property, which returns null

### ISSUE THREAD

**Issue by jykae** [apinf/api-umbrella-dashboard#714]
Found a bug from the recent develop version, I am getting error from elasticSearch.js from line 22. 

Exception while invoking method 'getChartData' TypeError: Cannot read property 'profile' of null
I20151215-14:02:54.605(2)?     at [object Object].Meteor.methods.getChartData (server/methods/elasticSearch.js:22:1)

**Comment by brylie** [comment]
@jykae please provide some steps to reproduce. Is this when you deploy? What is the context around this error?

**Comment by brylie** [comment]
@frenchbread is the [`chartsLayout` template](https://github.com/apinf/api-umbrella-dashboard/blob/develop/client/views/dashboard/charts/charts.js#L67 used in any routes where anonymous users can access? We may need to make sure the user is logged in before the `getChartsData` method is envoked, otherwise there needs to be a try catch around the [failing code](https://github.com/apinf/api-umbrella-dashboard/blob/develop/server/methods/elasticSearch.js#L5).

**Comment by frenchbread** [comment]
If i'm recalling correctly, `chartsLayout` template is not used in any routes. It is used in a `dashboard` template only. (Did some some search for `chartsLayout` occurrences within the project folder).

Tested this issue locally by calling `Meteor.call("getChartData")` and got similar error:
```
Exception while invoking method 'getChartData' TypeError: Cannot read property 'profile' of null
```
Seems like when deploying, `getChartData` gets called for some reason.

Agreed that error handling is needed there. What about checking if user isLoggedIn inside `getChartsData` method:
```javascript
if (Meteor.user())
    // continue getting charts data
else
   // terminate
```

**Comment by frenchbread** [comment]
Created a [hotfix](https://github.com/apinf/api-umbrella-dashboard/pull/721). Please review & test.

This should fix the problem now.

**Comment by brylie** [comment]
@frenchbread great work!
