### ISSUE TITLE
Create one automated test case

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#744]
Our code base currently has no automated unit or functional tests. If we can successfully create and execute one test case and run it against nightly deployment, we should be able to repeat it for remaining code base (or some portion of it).

Example test case: 
* Check whether search box appears on search result page. (Should not appear).
* Optionally, test whether is appears on front page. (Should appear.)

Choose the testing framework as well.

Definition of done
---
* [x] Testing framework is added to project.
* [x] Test exists for checking for search box.
  * [x] Test case exists for checking whether search box appears on search result page.
  * [x] Test case exists for checking whether search box appears on front page. (Currently testing`/catalogue` page. For front page need to use authorization module for "manual" authentication, which is not coded yet)
* [x] Test runs locally and can be demonstrated to the team.

**Comment by jykae** [comment]
@frenchbread FYI nightly.apinf,io is using this approach https://sungwoncho.io/meteorjs-continuous-delivery/ 

Mocha & Velocity are used there.

**Comment by frenchbread** [comment]
Created PR #772 under `WIP` label but can be reviewed already.

Two test cases:
* Check that `header-search-form` is missing on a `/search` page.
* Check that `header-search-form` exists on a `/catalogue` page. (Testing `/catalogue` page here, because for others there is a need to authenticate a test user, to be able to see content of other pages like `/dashboard` for example.)

Even though, "search form existence check" fails sometimes because elements on a target page load slower than test runs. Tried wrapping it around `setTimeout(..)`, throws an error:
```
Exception in setTimeout callback: Error: 'expect' was used when there was no current spec, this could be because an asynchronous test timed out
```
But it is successfully used in [this tutorial](http://experimentsinmeteor.com/meteor-testing-with-velocity-and-jasmine-part-2/).

More reference - [Jasmine integration tests with iron router](https://meteor-testing.readme.io/docs/jasmine-integration-tests-with-iron-router).

**Comment by brylie** [comment]
Can you use any `onLoad` or `ready` check here? E.g. [`jQuery.ready()`](https://api.jquery.com/ready/)?

**Comment by brylie** [comment]
Also, Telescope uses an [explicit template render function](https://github.com/TelescopeJS/Telescope/blob/master/tests/jasmine/client/unit/navSpec.js#L15-L20). E.g. they make sure to render() the template inside each test case.

**Comment by frenchbread** [comment]
Thanks.

**Comment by frenchbread** [comment]
Works now.

**Comment by frenchbread** [comment]
@brylie Wondering how to "hide" testing window while running on production. Does it require Travis CI setting for it? As @jykae suggested, this should do the thing:
```
- meteor --test --release velocity:METEOR@1.2.1
```
Or we can use separate branch specifically for testing.

**Comment by brylie** [comment]
I think testing is automatically disabled in production deployments.

**Comment by frenchbread** [comment]
Ok, cool then. Please review this PR.

**Comment by brylie** [comment]
@frenchbread lets try running our tests using [Intern](https://theintern.github.io/). We can still use the Jasmine TDD language, so you might not have to re-write your tests.

**Comment by brylie** [comment]
Also, I reorganized the tests and simplified the code. Both tests now work in Velocity, so we can stick with Velocity for the time being.

**Comment by frenchbread** [comment]
**Intern** looks good by the way. Wondering if it has meteor package (was not able to find it so far), but we can end up adding regular `.js` files to the project. 

It makes sense to switch because **Velocity** eats a lot of resources and **Intern** seems like can give access to the `Meteor` object, what we were not able to achieve when using **Velocity**.

[Good reference](https://gist.github.com/harpreetkhalsagtbit/55022792c1b6ab4367c4)

**Comment by brylie** [comment]
OK, cool. Maybe we can try Intern this sprint. If it is too difficult, your Velocity tests can be merged into develop.

**Comment by frenchbread** [comment]
I've managed to fire up unit testing with intern. Working branch: [`feature/theintern-automated-testing`](https://github.com/apinf/api-umbrella-dashboard/tree/feature/theintern-automated-testing)

Since intern is an npm package, it requires manual installation. (`npm i intern`)
#### Folder structure
```
tests/
    node_module/    <--- (currently ignored in .gitignore)
        intern
    tests/
        unit/
            test.js
    intern.js    <--- (config file)
```

#### Run tests
**Unit:**
```
$ node_modules/.bin/intern-client config=tests/intern`
```
**Functional:**
```
$ node_modules/.bin/intern-runner config=tests/intern
```

**Comment by frenchbread** [comment]
When starting up `intern-runner` it throws an error:
```
Error: The tunnel reported: You provided an invalid key
```
As noted [here](https://github.com/theintern/intern-tutorial#step-5-everything-all-together), its needed to provide username & access key but even with them I get the same error.

@brylie Any ideas?

**Comment by brylie** [comment]
We probably don't need to configure a tunnel at this point. E.g. it should be possible to run the tests locally, without tunneling to any remote service.

**Comment by brylie** [comment]
Are you able to run the tests locally?

**Comment by brylie** [comment]
Check the [running tests](https://theintern.github.io/intern/#browser-client) documentation for several ways to run the tests locally.

**Comment by frenchbread** [comment]
@brylie I was able to run sample tests only. Gotta figure out how to redirect to other pages..

**Comment by brylie** [comment]
Ah, OK. Well, good progress though :-)

**Comment by brylie** [comment]
It might be a matter of [calling `get(url)`](https://theintern.github.io/leadfoot/Session.html#get).

**Comment by frenchbread** [comment]
@brylie Yeah, that's what I tried.
As in this example:
```javascript
registerSuite({
        name: 'index',

        'greeting form': function () {
            var rem = this.remote;
            return this.remote
                .get(require.toUrl('localhost:3000'))
                .setFindTimeout(5000)
                .execute(function() {
                        console.log("browser window object", window)
                        return Products.find({}).fetch().length
                    })
                .then(function (text) {
                    console.log(text)
                    assert.strictEqual(text, 2,
                        'Yes I can access Meteor and its Collections');
                });
        }
});
```
... method `get(require.toUrl(url))` is attached to `this` instance. And `this` returned `null` value. For that reason I thought that I have to run it through `intern-runner`.

Seems like `get(url)` is different approach, will try it.

**Comment by frenchbread** [comment]
Getting `TypeError: Cannot read property 'get' of null`..

**Comment by frenchbread** [comment]
`this` instance is undefined inside testing function

**Comment by brylie** [comment]
Try saving `this` as a named variable, outside of the test function.

**Comment by frenchbread** [comment]
@brylie Could you help with this one? I think that `intern-runner` is needed for our purposes, since we want to test "page state" at a specific URL. In this case this test is a functional and as far as I understand needs to be run using `intern-runner`.

**Comment by brylie** [comment]
OK, cool. I will take a look.
