### ISSUE TITLE
Demonstrate progress in a Meteor learning course

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#87]
Choose a learning framework for Meteor.js. Make demonstrable progress through the learning resource (e.g. complete chapters, demonstration code).

Definition of done:
* [ ] Some demonstrable artifact showing progress through a Meteor.js learning resource/framework

**Comment by frenchbread** [comment]
As a progress demonstration, I have build an extended To-Do List app which is based on tutorial provided in meteor documentation. (https://github.com/frenchbread/Todo-list) 

Besides the basic to-do list, I have added the functionality of creating lists and sorting tasks by these lists. I was not paying much attention to web-design because the main point of this app is learning meteor.
